### ISSUE TITLE
Panic when setting parent branch

### ISSUE THREAD

**Issue by Iron-Ham** [git-town/git-town#2712] opened 2023-12-01 00:00 UTC
I made an invocation of `git-town new-pull-request` on a branch whose parent had not been set by `git-town`.

I copied the parent-branch name, but the copy, unbenownst to me, had a `\n` at its head. 

Now, git-town is stuck in this perpetual state, regardless of which action I attempt. 

```
➜ git sync
panic: local branch names cannot be empty

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewLocalBranchName(...)
	github.com/git-town/git-town/v10/src/domain/local_branch_name.go:14
github.com/git-town/git-town/v10/src/config.(*GitTown).Lineage(0x140001af0e0, 0x1400015d188)
	github.com/git-town/git-town/v10/src/config/git_town.go:139 +0x2b4
github.com/git-town/git-town/v10/src/cmd.determineSyncConfig(0x0, 0x140001ad360, 0x0)
	github.com/git-town/git-town/v10/src/cmd/sync.go:130 +0x6c
github.com/git-town/git-town/v10/src/cmd.executeSync(0x0?, 0x0?, 0x0)
	github.com/git-town/git-town/v10/src/cmd/sync.go:69 +0x78
github.com/git-town/git-town/v10/src/cmd.syncCmd.func1(0x140001be500?, {0x1052f4e20?, 0x4?, 0x104bb8617?})
	github.com/git-town/git-town/v10/src/cmd/sync.go:48 +0x74
github.com/spf13/cobra.(*Command).execute(0x140001c6300, {0x1052f4e20, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a2000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
	github.com/git-town/git-town/v10/src/cmd/core.go:33 +0x308
main.main()
	github.com/git-town/git-town/v10/main.go:22 +0x30

```

**Comment by kevgo** [comment] 2023-12-01 02:13
Please run `git town config reset`. This will delete all Git Town configuration and should remove the invalid config entry that causes this problem. At the next invocation, Git Town will ask you to set the main and perennial branches again.

**Comment by Iron-Ham** [comment] 2023-12-01 03:57
@kevgo no dice.

```
mobile-ios on  hs/actor-isolation [$!] via ⬢ v18.16.0 via 💎 v3.1.1
➜ git-town config reset

mobile-ios on  hs/actor-isolation [$!] via ⬢ v18.16.0 via 💎 v3.1.1
➜ git new-pull-request
panic: local branch names cannot be empty

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewLocalBranchName(...)
	github.com/git-town/git-town/v10/src/domain/local_branch_name.go:14
github.com/git-town/git-town/v10/src/config.(*GitTown).Lineage(0x140001af140, 0x1400015d458)
	github.com/git-town/git-town/v10/src/config/git_town.go:139 +0x2b4
github.com/git-town/git-town/v10/src/cmd.determineNewPullRequestConfig(0x140001ad400, 0x0)
	github.com/git-town/git-town/v10/src/cmd/new_pull_request.go:109 +0x6c
github.com/git-town/git-town/v10/src/cmd.executeNewPullRequest(0x0)
	github.com/git-town/git-town/v10/src/cmd/new_pull_request.go:66 +0x68
github.com/git-town/git-town/v10/src/cmd.newPullRequestCommand.func1(0x140001bed00?, {0x1039a0e20?, 0x4?, 0x103264617?})
	github.com/git-town/git-town/v10/src/cmd/new_pull_request.go:47 +0x28
github.com/spf13/cobra.(*Command).execute(0x140001b2300, {0x1039a0e20, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a2000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
	github.com/git-town/git-town/v10/src/cmd/core.go:33 +0x308
main.main()
	github.com/git-town/git-town/v10/main.go:22 +0x30
```

**Comment by Iron-Ham** [comment] 2023-12-11 19:57
Thank you @kevgo.
I've uninstalled and reinstalled it prior to the release (which worked). Hopefully the source of this can be found.

**Comment by kevgo** [comment] 2023-12-13 02:44
Great to hear @Iron-Ham! Regarding the bug where you pasted a branch name containing a newline character and were left with a non-working Git Town setup, I cannot reproduce it on macOS, Linux (Fedora), or Windows. The input library that Git Town uses seems to correctly trim leading and trailing newlines from entered text. Can you provide more information about your environment and which particular steps you took?

**Comment by Iron-Ham** [comment] 2023-12-13 04:21
I'm on macOS Sonoma. I cannot assume how the branch name copied when I pulled it from my GitHub PR. It could have pulled as:

```

hs/update-generation
```

Or alternatively:

```
Iron-Ham wants to merge 1 commit into hs/remove-unused-imports from hs/remove-statefulcancellable
```

**Comment by kevgo** [comment] 2023-12-17 00:20
Okay, thanks for the additional info. Given that there is no more actionable item for this ticket at this point, I'm closing it. If you run into this issue again, or have a working repro, please comment and I'll reopen it. I'm glad this ticket has already led to an improvement that removes Git Town configuration more thoroughly!

**Closed by kevgo** 2023-12-17 00:20 UTC
Labels: bug
