### ISSUE TITLE
no alias sub-command

### ISSUE THREAD

**Issue by kelbyers** [git-town/git-town#2178] opened 2023-03-21 15:20 UTC
The instructions for configuring and for uninstalling `git town` both mention using the `git town alias` sub-command. That command does not seem to exist in version v7.9.0:

```
➜ git town version
Git Town v7.9.0 (2023/01/22)

➜ git town alias true
Error: unknown command "alias" for "git-town"
Run 'git-town --help' for usage.

Error: unknown command "alias" for "git-town"
```

From the "Quick configuration" section of the documentation:

Having to type git town <command> gets old. Git Town can install aliases for its commands that make them feel like native Git commands, i.e. allow you to run for example git hack instead of git town hack. To enable this feature:

git town alias true

To remove these aliases, run git town alias false.

**Comment by kevgo** [comment] 2023-03-28 01:28
Thanks for reporting this. I just downloaded v7.9 from the [release page](https://github.com/git-town/git-town/releases/tag/v7.9.0) and `git town alias true` works. Can you please share how you installed Git Town on your machine?

**Comment by kelbyers** [comment] 2023-04-17 14:24
Sorry, I seem to have missed the notification for this. I am on a Mac, and installed git-town using homebrew:

```
brew install git-town
```

**Comment by kevgo** [comment] 2023-04-17 20:14
Okay, thanks for the getting back about this. I'm going to close this issue given that the problem is resolved now.

**Closed by kevgo** 2023-04-17 20:14 UTC
