### ISSUE TITLE
Is creating a new "prototype" branch supposed to push the branch?

### ISSUE THREAD

**Issue by kelbyers** [git-town/git-town#3846] opened 2024-08-13 15:52 UTC
### Your message to us

I created a new prototype branch, using `git town hack --prototype`, and it got pushed to my remote. I had thought, from reading the docs, that it would not be pushed or tracked, but it was.

Did I misunderstand this branch type, or did I create it incorrectly?

```
❯ git town hack --prototype testing/prom_metrics
Git Town needs to be configured

Main branch: main
Perennial branches: (none)

[main] git add -A

[main] git stash
Saved working directory and index state WIP on main: 894fdc5 added a README

[main] git checkout -b testing/prom_metrics
Switched to a new branch 'testing/prom_metrics'

[testing/prom_metrics] git push -u origin testing/prom_metrics
```

`git remote show origin` shows:
```
  Remote branches:
    main                 tracked
    testing/prom_metrics tracked
  Local branches configured for 'git pull':
    main                 merges with remote main
    testing/prom_metrics merges with remote testing/prom_metrics
  Local refs configured for 'git push':
    main                 pushes to main                 (up to date)
    testing/prom_metrics pushes to testing/prom_metrics (up to date)
```

**Comment by kevgo** [comment] 2024-08-22 01:35
Hmm, I cannot reproduce this problem. On my machine:

```
> git town hack --prototype testing/prom_metrics

[main] git fetch --prune --tags

[main] git rebase origin/main
Current branch main is up to date.

[main] git checkout -b testing/prom_metrics
Switched to a new branch 'testing/prom_metrics'
```

Maybe the dialog for the configuration messed something up here?

**Comment by kevgo** [comment] 2024-08-22 01:37
I tried it on another unconfigured repo and it works there as well:

```
> git town hack --prototype testing/prom_metrics

[main] git fetch --prune --tags
Git Town needs to be configured

Main branch: main

[main] git rebase origin/main
Current branch main is up to date.

[main] git checkout -b testing/prom_metrics
Switched to a new branch 'testing/prom_metrics'
```

**Comment by kevgo** [comment] 2024-08-22 01:45
To answer your question: You’re spot on. Creating a new prototype branch doesn’t (shouldn't) push that branch.

I’m going to close this issue as "cannot reproduce." If you have more insights or run into this problem again, just drop a comment and I’ll reopen it. If it happens again, please share the output of `git town hack --prototype --verbose <branch name>`. Thanks!

**Closed by kevgo** 2024-08-22 01:45 UTC
