### ISSUE TITLE
git town confuses branches on sync and then panics

### ISSUE THREAD

**Issue by zepatrik** [git-town/git-town#1643] opened 2020-11-03 12:26 UTC
I just ran into a weird case where git town seems to confuse branches and panic after I try to abort the merge.
Note that I am on branch `argon2-value-cli` and `schema-improvements` is some other old branch.

```
[patrik@patrik-x1 docs]$ git sync

[argon2-value-cli] git fetch --prune --tags
From github.com:ory/kratos
 - [deleted]           (none)     -> origin/move-pkgerx
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 49 (delta 41), reused 42 (delta 41), pack-reused 2
Unpacking objects: 100% (49/49), 7.32 KiB | 214.00 KiB/s, done.
   a6838cdd..e351d713  argon2-value-cli -> origin/argon2-value-cli
   aa1e3924..60a0fc44  master           -> origin/master

cd /home/patrik/git/kratos

[argon2-value-cli] git checkout master
Switched to branch 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

[master] git rebase origin/master
Successfully rebased and updated refs/heads/master.

[master] git checkout argon2-value-cli
Switched to branch 'argon2-value-cli'
Your branch and 'origin/argon2-value-cli' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

[argon2-value-cli] git merge --no-edit origin/argon2-value-cli
Merge made by the 'recursive' strategy.
 docs/docs/cli/kratos-hashers-argon2-calibrate.md |   2 +-
 docs/sidebar.json                                | 138 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------
 2 files changed, 70 insertions(+), 70 deletions(-)

[argon2-value-cli] git merge --no-edit master
Removing x/pkger.go
Auto-merging go.sum
CONFLICT (content): Merge conflict in go.sum
Auto-merging go.mod
CONFLICT (content): Merge conflict in go.mod
Automatic merge failed; fix conflicts and then commit the result.

Error: exit status 1

To abort, run "git-town abort".
To continue after having resolved conflicts, run "git-town continue".
To continue by skipping the current branch, run "git-town skip".


[patrik@patrik-x1 docs]$ git-town continue

[argon2-value-cli] git push
Enumerating objects: 24, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 4 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 3.51 KiB | 1.75 MiB/s, done.
Total 10 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To github.com:ory/kratos.git
   e351d713..64a2b962  argon2-value-cli -> argon2-value-cli

Error: cannot check out branch "schema-improvements" in repo ".": exit status 1
&{git [checkout schema-improvements] error: Your local changes to the following files would be overwritten by checkout:
        go.mod
        internal/testhelpers/selfservice_settings.go
        selfservice/flow/settings/handler_test.go
        selfservice/strategy/link/strategy_recovery.go
        selfservice/strategy/link/strategy_verification.go
        selfservice/strategy/password/login.go
        selfservice/strategy/password/login_test.go
        selfservice/strategy/password/registration.go
        selfservice/strategy/password/registration_test.go
        selfservice/strategy/password/settings.go
        selfservice/strategy/password/settings_test.go
        selfservice/strategy/profile/strategy.go
        selfservice/strategy/profile/strategy_test.go
        x/nosurf.go
Please commit your changes or stash them before you switch branches.
Aborting
}

To abort, run "git-town abort".
To continue after having resolved conflicts, run "git-town continue".
To continue by skipping the current branch, run "git-town skip".


[patrik@patrik-x1 docs]$ git-town abort

[argon2-value-cli] git merge --abort
error: Entry 'go.mod' not uptodate. Cannot merge.
fatal: Could not reset index file to revision 'HEAD'.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7babfd]

goroutine 1 [running]:
github.com/git-town/git-town/src/run.(*Result).Output(...)
        C:/Users/kevin/d/git-town/src/run/result.go:36
github.com/git-town/git-town/src/git.(*Runner).AbortMerge(0xc00018e048, 0x9251e0, 0xdde5e8)
        C:/Users/kevin/d/git-town/src/git/runner.go:35 +0xbd
github.com/git-town/git-town/src/steps.(*AbortMergeBranchStep).Run(0xdde5e8, 0xc00018e000, 0xa4e880, 0xc000149e30, 0xdb47a0, 0x7fe31036e560)
        C:/Users/kevin/d/git-town/src/steps/abort_merge_branch_step.go:15 +0x31
github.com/git-town/git-town/src/steps.Run(0xc00014c150, 0xc00018e000, 0xa4e880, 0xc000149e30, 0x9b7278, 0xa4e880)
        C:/Users/kevin/d/git-town/src/steps/run.go:43 +0x15f
github.com/git-town/git-town/src/cmd.glob..func1(0xdad1a0, 0xdde5e8, 0x0, 0x0)
        C:/Users/kevin/d/git-town/src/cmd/abort.go:25 +0x32b
github.com/spf13/cobra.(*Command).execute(0xdad1a0, 0xdde5e8, 0x0, 0x0, 0xdad1a0, 0xdde5e8)
        C:/Users/kevin/d/git-town/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xda97e0, 0x2, 0x1c, 0x0)
        C:/Users/kevin/d/git-town/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/kevin/d/git-town/vendor/github.com/spf13/cobra/command.go:887
github.com/git-town/git-town/src/cmd.Execute()
        C:/Users/kevin/d/git-town/src/cmd/root.go:34 +0x71
main.main()
        C:/Users/kevin/d/git-town/main.go:10 +0x20
[patrik@patrik-x1 docs]$ git-town version
Git Town v7.4.0 (2020-07-05T13:06:34Z)
```

**Comment by kevgo** [comment] 2020-11-22 17:06
Thanks for the detailed bug report, Patrick! I think there are several problems here:

1. the root cause is related to #1637: `git town continue` mistakenly skips committing the open changes and therefore cannot check out the next branch.
2. `git town continue` tries to check out an old branch (`schema-improvements`) instead of the branch on which `git town sync` was started (`argon2-value-cli`)
3. `git merge --abort` fails with uncommitted changes because `Entry 'go.mod' not uptodate`. 
4. Problem 3 causes a nil pointer dereference in https://github.com/git-town/git-town/blob/master/src/run/result.go#L36

We have [end-to-end tests for scenario 3 and 4](https://github.com/git-town/git-town/blob/master/features/sync/current_branch/feature_branch/conflicts/feature_branch_merge_main_branch_conflict/with_tracking_branch_updates.feature) so I'm surprised this happens. Maybe newer Git versions have different output that breaks Git Town's detection of command output. Can you please let me know which Git version you run, or if you use any special Git configuration? Thanks!

**Comment by zepatrik** [comment] 2020-11-22 19:58
```
$ git --version
git version 2.29.2
```
There is no special config or modding applied to git.

**Comment by kevgo** [comment] 2020-11-22 20:00
Thanks! And thanks for the confirmation about the subdirectory. This is super helpful!

**Comment by kevgo** [comment] 2023-12-08 21:30
Here is what I think happened:

- You run `git sync` on the `argon2-value-cli` branch.
- The files `go.mod` and `go.sum` on that branch conflict with updates on `master`.
- I assume you resolve this merge conflict and commit the changes offscreen.
- I think you also leave some uncommitted/untracked changes in your workspace during this:

  ```
  internal/testhelpers/selfservice_settings.go
  selfservice/flow/settings/handler_test.go
  selfservice/strategy/link/strategy_recovery.go
  selfservice/strategy/link/strategy_verification.go
  selfservice/strategy/password/login.go
  selfservice/strategy/password/login_test.go
  selfservice/strategy/password/registration.go
  selfservice/strategy/password/registration_test.go
  selfservice/strategy/password/settings.go
  selfservice/strategy/password/settings_test.go
  selfservice/strategy/profile/strategy.go
  selfservice/strategy/profile/strategy_test.go
  x/nosurf.go
  ``` 
- Git Town finishes the sync.
- Git Town tries to check out the `schema-improvements` branch. Git Town does this to make sure `git checkout -` behaves the same before and after running `git sync`. This fails because the untracked changes in your workspace conflict with `schema-improvements`.
- Git Town doesn't handle this error well because it can never happens under normal circumstances since the workspace is always clean here. Due to the bug in `git town continue`, it does happen and Git Town prints a misleading error message encouraging to run `git town abort`. 
- You run `git town abort`. Git Town again doesn't handle an error that should never happen well. It runs the wrong abort command and crashes.

The root cause of the problem is that `git town continue` allowed untracked files. https://github.com/git-town/git-town/issues/2753 fixes this. There were also some issues with persisting state properly when a Git Town command gets interrupted multiple times. This is fixed as well.

I think all issues described by this ticket have been addressed and the described problem cannot happen any longer. I'm therefore going to close this ticket. Thanks again for the detailed report about an interesting edge case!

**Closed by kevgo** 2023-12-08 21:30 UTC
Labels: bug
