### ISSUE TITLE
Handling of "+" character at "git-town sync"

### ISSUE THREAD

**Issue by koppor** [git-town/git-town#2196] opened 2023-04-05 05:41 UTC
My output of `git branch` looks as follows:

![image](https://user-images.githubusercontent.com/1366654/229990616-b61da729-e1a1-447a-8047-c1e2b2f9d593.png)

I think, the character `+` appears, because of my usage of "git worktree"

If I now execute "git-town sync", it offers me `+ main` as branch:

![image](https://user-images.githubusercontent.com/1366654/229990794-3bbf4a3d-10ab-440e-b203-69b65ac61e33.png)

After selecting that, the output is as follows:

![image](https://user-images.githubusercontent.com/1366654/229990877-a86fdc62-9ae4-43b4-8210-342156062fca.png)

I think, git-town should drop `+ ` as it also drops `* ` at branch name detection.

**Comment by kevgo** [comment] 2023-04-05 19:49
You are right, Git Town currently does not support Git worktrees (but should). This ticket seems a duplicate of https://github.com/git-town/git-town/issues/2134. Let's continue the conversation there. Please also upvote that ticket to help prioritize it. Thanks!

**Closed** 2023-04-05 19:50 UTC
