### ISSUE TITLE
question/feature request: `-o ci.skip` on sync?

### ISSUE THREAD

**Issue by bryanlarsen** [git-town/git-town#3542] opened 2024-05-23 19:08 UTC
I'm 7 deep in my merge stack (which will all merge today, yay!), and every time I hit sync to rebase onto main it starts up 7 CI pipelines which blocks CI for everybody.   I then manually cancel all but top of stack.

Is there a way to pass `-o ci.skip` to the pushes on a sync to prevent this?

**Comment by kevgo** [comment] 2024-05-23 19:56
I agree this is an important missing feature. There is a ticket (https://github.com/git-town/git-town/issues/999) for planning and gathering ideas around this idea. Am I correct to assume that the `-o ci.skip` trick works only on GitLab?

**Comment by bryanlarsen** [comment] 2024-05-23 19:59
github too: https://docs.gitlab.com/ee/user/project/push_options.html

**Comment by kevgo** [comment] 2024-05-23 20:04
The link you shared seems to document GitLab's behavior, not GitHub's. Am I missing something? For GitHub, I have found this: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

**Comment by kevgo** [comment] 2024-06-17 21:51
Closing as duplicate of #999. Let's continue the conversation there!

**Closed by kevgo** 2024-06-17 21:51 UTC
