### ISSUE TITLE
Support "--version"

### ISSUE THREAD

**Issue by koppor** [git-town/git-town#2429] opened 2023-08-29 07:06 UTC
Typical linux shell tools offer `--version` and output their version.

Example:

```terminal
$ git --version
git version 2.42.0.windows.1
```

git-town should also offer it:

```terminal
$ git-town --version

Error: unknown flag: --version
```

**Comment by kevgo** [comment] 2023-08-30 02:35
Git Town follows the behavior of the Go compiler:

```
$ go version
go version go1.20.6 darwin/arm64
```

So, as of now, you check the version of Git Town this way:

```
$ git town version
Git Town v9.0.1-79-g7ba310bf-dev (2023-08-28)
``` 

You make a good point that Git Town should follow the behavior of Git where possible since it is semantically closer to Git than to the Go compiler. In my example it's even called through Git! Let's change the version check to what you propose.

**Comment by kevgo** [comment] 2023-11-02 00:50
FYI this has been released as [v10.0.0](https://github.com/git-town/git-town/releases/tag/v10.0.0). Apologies for the delay, this PR came in the middle of a large-scale product cleanup that involved a number of breaking changes that need to be shipped together but took a while to finalize and test.

**Comment by koppor** [comment] 2023-12-21 13:38
It used to work, but the latest version does not display any version:

```
C:\Users\koppor>git-town -V
Git Town  ()

C:\Users\koppor>which git-town
/c/Program Files (x86)/Git Town/git-town
```

Installed using `git-town_windows_intel_64.msi` retrieved from https://github.com/git-town/git-town/releases/download/v11.1.0/git-town_windows_intel_64.msi (linked from https://www.git-town.com/install.html#windows as of today)

**Comment by koppor** [comment] 2023-12-21 13:39
"version" does not work anymore:

```
C:\Users\koppor>git-town version

Error: unknown command "version" for "git-town"


C:\Users\koppor>git town version

Error: unknown command "version" for "git-town"
```

**Comment by kevgo** [comment] 2024-01-03 22:47
v10.0 removed `git town version` and added `git town --version` in https://github.com/git-town/git-town/pull/2603 following your suggestion in this ticket.

I can reproduce the broken version output in the executable that gets installed via the MSI file. Strangely enough, the executable in the ZIP file works correctly, and the MSI only packages that executable. I'll look into this during the next release.

**Comment by lud-wj** [comment] 2024-01-16 15:31
I just installed the release `v11.1.0` with `git-town_linux_intel_64.deb` and I have this output:

```
git-town --version
Git Town v10.0.3 (2023-12-12)
```

The release date seems to match the release date (so hopefully my upgrade went well, but the version number is wrong.

**Comment by kevgo** [comment] 2024-01-16 15:49
@lud-wj you are running version v11.1. This version has a bug that makes it report an  incorrect version. The fix for this will go out in the next release. Apologies for the bug and thanks for checking in!

**Closed** 2024-02-09 21:13 UTC

**Comment by kevgo** [comment] 2024-02-09 21:15
Apologies, this is still broken in v12.0.0. I have now replaced the old (and flimsy) way of displaying the version with a simple hard-code version that will always work and is now better covered by an end-to-end tests. This will go out in v12.0.1.
