### ISSUE TITLE
How to switch parent for a child branch, after its parent has been merged to master

### ISSUE THREAD

**Issue by breml** [git-town/git-town#3298] opened 2024-04-04 06:59 UTC
I have the following situation:

```
master
  parent-branch
    child-branch
```

For both, `parent-branch` and `child-branch` I have a PR on Github. Both PR are reviewed and approved so they are ready to be shipped. Since I can not use `git town ship`, I would first merge the PR of the `parent-branch` on Github. The merge is happening with a *squash merge* and those the history is rewritten and does no longer match the history the `child` branch sees.

After this step, I am unsure how to continue using Git Town, since now Git Town is not aware of the merge.

What I would normally do (without Git Town) are the following steps (hopefully the list is complete, I have written this down just from memory):

```
git fetch -a --prune
# at this stage, origin/parent-branch will be removed
git checkout child-branch
git rebase --onto origin/master parent-branch
git push -f # i guess using --force-with-lease --force-if-includes would be saver, but I am lazy
git checkout master
git branch -D parent-branch
```

Now I am ready to also merge the `child-branch` (target to merge to on Github was originally the `parent-branch`, but when this one got merged on Github, the target is automatically updated to `master`).

How would the necessary steps look like with Git Town? Do I have to update the parent manually? Does Git Town allow `rebase --onto` to ease the rebase after a *squash merge* of the parent?

For a more in-depth explanation of `git rebase --onto` have a look at https://womanonrails.com/git-rebase-onto (replace the current parent branch).

**Comment by kevgo** [comment] 2024-04-05 15:29
I have added the missing end-to-end tests that demonstrate how Git Town deals with the scenario you describe right now. If there are better things that Git Town could do here, let's implement them!

- Exact reproduction of the scenario you describe: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/stacked_changes/parent_shipped.feature
- When you have shipped multiple ancestor branches: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/stacked_changes/ancestors_shipped.feature

**Comment by breml** [comment] 2024-04-05 20:08
> I have added the missing end-to-end tests that demonstrate how Git Town deals with the scenario you describe right now. If there are better things that Git Town could do here, let's implement them!
> 
> * Exact reproduction of the scenario you describe: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/stacked_changes/parent_shipped.feature

I had a look at the end-to-end test description and I wonder, why on line 22 a `git rebase main` is done, only to then delete the branch on line 24  with `git branch -D parent`. Does this make any sense?

If you consider to support `--onto` in the future, the order of the commands would need to change, since the `git rebase --onto master parent` would need to happen before the `parent` branch is deleted.

**Comment by kevgo** [comment] 2024-04-06 01:55
> I had a look at the end-to-end test description and I wonder, why on line 22 a git rebase main is done, only to then delete the branch on line 24 with git branch -D parent. 

Git Town deletes local branches whose tracking branch is gone, but only if the local branch doesn't contain unshipped changes. To check for unshipped changes, Git Town syncs the local branch first (using `git rebase main`). Then it runs `git diff main..branch`. Only if that turns out empty does it delete the local branch. Git Town currently does not display the `git diff` command but runs it in the background. You can see it when using the `--verbose` option: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/tracking_branch/deleted/verbose.feature#L32. 

Maybe it would be helpful to display the `git diff` command in the foreground.

**Comment by kevgo** [comment] 2024-04-06 01:56
Feature spec for not deleting a local branch that contains commits that weren't pushed before the branch was shipped remotely: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/tracking_branch/deleted/unmerged_local_commits.feature

Feature spec for not deleting a local branch that was deleted at the remote but contains unmerged local changes: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/tracking_branch/deleted/deleted_unmerged_branch.feature

**Comment by breml** [comment] 2024-04-06 05:14
> > I had a look at the end-to-end test description and I wonder, why on line 22 a git rebase main is done, only to then delete the branch on line 24 with git branch -D parent.
> 
> Git Town deletes local branches whose tracking branch is gone, but only if the local branch doesn't contain unshipped changes. To check for unshipped changes, Git Town syncs the local branch first (using `git rebase main`). Then it runs `git diff main..branch`. Only if that turns out empty does it delete the local branch. Git Town currently does not display the `git diff` command but runs it in the background. You can see it when using the `--verbose` option: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/tracking_branch/deleted/verbose.feature#L32.
> 
> Maybe it would be helpful to display the `git diff` command in the foreground.

I think running `git diff` in the background is fine. My question was more about: if Git Town already "knows", that the tracking branch has gone due to the `git fetch -a --prune` at the beginning, why does it sync the "to be deleted" branch. But your argument is valid, that the branch is only deleted, if there are no changes left, that have not yet been merged to main. So forget about my comment.

**Comment by kevgo** [comment] 2024-04-13 14:28
I think this ticket is answered. I'm going to close it for now. If you have further questions around this, please don't hesitate to comment or re-open. Thanks!

**Closed by kevgo** 2024-04-13 14:28 UTC

**Comment by kevgo** [comment] 2024-11-02 12:37
@breml Thanks for your patience—I think I misunderstood your initial point on this ticket. I don’t use the rebase strategy on feature branches myself, so I hadn’t encountered this issue firsthand. Recently, though, someone provided a detailed step-by-step reproduction that allowed me to replicate the problem, and I’ve now added it to the backlog: https://github.com/git-town/git-town/issues/4189.

Is this aligned with the solution you had in mind? Thanks again for your insights! 🙏

**Comment by breml** [comment] 2024-11-26 17:46
@kevgo Sorry for not being responsive on this issue. I am with a new project since this month, where I currently do not need rebase strategy and therefore currently use plain git without git town. Additionally, there is currently too much on my plate so I do not have the time to look into this issue. I am sorry.

**Comment by kevgo** [comment] 2024-11-26 19:18
No worries at all&mdash;really appreciate all the excellent feedback you’ve shared! Just to note, even if branch stacks or rebasing aren’t part of your workflow, `git sync` and `git propose` can still be super helpful for development. Best of luck with your new project, and feel free to circle back in the future 🚀
