### ISSUE TITLE
`git town undo` mysteriously force-pushed to a bunch of unrelated feature branches

### ISSUE THREAD

**Issue by ianjsikes** [git-town/git-town#3763] opened 2024-07-25 15:14 UTC
### Your message to us

I work on a large monorepo with a lot of concurrent development going on. I had two feature branches, `feature-one` and `feature-two`, both branched off of `main`. I wanted to re-arrange them so that `feature-two`'s parent was `feature-one`, to replicate the "stacked diffs"-type workflow. I ran `git town set-parent` and set `feature-one` as the parent.

From this point, `git town` started doing it's thing, updating branches, etc. I ran into a merge conflict, which is no big deal. But in the process of looking at the merge conflict, I realized I didn't actually want to do this rebase anymore, and the branches were fine as-is. So I ran `git town undo`, thinking this would roll back the changes _to my two branches_. But git-town had something else in mind.

For reasons I can not understand, it started running `git push --force-with-lease origin GITHASH:feature/my-coworkers-branches` on a ton of different branches in quick succession. None of these branches have been checked out locally, nor have I ever even touched them. THANKFULLY, git-town eventually tried to do this with `main` and failed due to GitHub branch protection, otherwise I assume it would have done this to EVERY branch on the remote.

This caused a huge incident, where I suddenly had to look through the command output, find all the affected branches, look up the git author, search them up on Slack, apologize profusely, and ask them to kindly force-push their local branch back up to undo the damage. In one case, it even caused a PR to be closed with the remote branch being deleted.

So I guess my question is, what happened here? Why did git-town decide it needed to force-push a lot of branches that I had never once touched? Is there some config option that I misunderstood? Is my computer haunted? I'm proficient enough with git to use it for day-to-day development, but I am far far far from an expert, so I'm not ruling out PEBKAC, but this seems bizarre. I feel like this must be a bug, because the description for `git town undo` says:
> The undo command reverts the last fully executed Git Town command. It performs the opposite activities that the last command did and **leaves your repository in the state it was before you ran the problematic command**.

I have been loving git-town since I started using it, to the point where I pitched it to my whole team and they recently started using it too. But after this I warned them to stop completely because I'm scared of the damage it might do.

**Comment by kevgo** [comment] 2024-07-25 21:34
Hey, thanks for the bug report! And sorry for the hassle you ran into. This isn't on you - support for mono-repos is still a work in progress and it looks like you ran into an edge case that Git Town doesn't handle correctly right now. The good news is that your feedback is going to help us fix this faster.

Here's what's going on: When you run a Git Town command like git sync, it does these things:

1. Take a "before snapshot" of all branches (local and remote).
2. Do its thing, like syncing branches.
3. Take an "after snapshot" of all branches (local and remote).

Then, when you run `git town undo`, it:

4. Calculates the difference between the before and after snapshots.
5. Resets all your Git branches (local and remote) to their state in the "before snapshot".

In your case, it seems something like your IDE or a background process ran `git fetch` between the two snapshots. This made some of your coworkers' branches get new SHAs, and maybe even added new coworker branches to the "after snapshot."

Git Town then (wrongly) assumes you made or updated all these remote branches while resolving conflicts. So it resets all these branches to their previous SHAs and deletes the new remote branches.

One way to fix this could be to undo only the changes to local branches and their tracking branches, and leave all remote-only branches alone.

Do you think this would have avoided the problem you encountered?

**Comment by kevgo** [comment] 2024-07-25 22:32
I have been able to reproduce the described behavior in an end-to-end test. https://github.com/git-town/git-town/blob/1819eec8f39737720c5693eefbfb6b14ec763865/features/sync/current_branch/feature_branch/fetch-in-between.feature#L47-L53

**Closed** 2024-07-26 02:08 UTC
Labels: bug

**Comment by kevgo** [comment] 2024-07-26 02:10
@ianjsikes I have committed the fix I was discussing earlier. I'll release a new version of Git Town containing this fix in the next day or two.

**Comment by kevgo** [comment] 2024-07-26 02:36
Another idea to prevent issues like this might be to confirm with the user before force-pushing or deleting remote branches as part of undo.

**Comment by kevgo** [comment] 2024-07-26 16:26
I have just released Git Town [v14.4](https://github.com/git-town/git-town/releases/tag/v14.4.0) that contains a fix for the severe bug described in this issue. Please update as soon as possible to avoid running into this issue again.

More mitigations discussed here and in #3765 will be released soon.

**Comment by kevgo** [comment] 2024-07-30 02:23
[v14.4.1](https://github.com/git-town/git-town/releases/tag/v14.4.1) ships even better protection against this problem.
